"""add_user_role

Revision ID: 793b6de1f5d5
Revises: d0f60537fd74
Create Date: 2024-03-27 15:43:50.010876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793b6de1f5d5'
down_revision: Union[str, None] = 'd0f60537fd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE TYPE role AS ENUM ('client', 'admin');"))
    op.add_column('users', sa.Column('role', sa.Enum('client', 'admin', name='role'), server_default='client', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute(sa.text("DROP TYPE IF EXISTS role;"))
    # ### end Alembic commands ###
